name: macOS

on:
  push:
    branches: [ jdk-17+35-mac ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: bash configure --enable-debug --with-jvm-variants=server --disable-warnings-as-errors
    - run: make images
    - run: ./build/*/images/jdk/bin/java -version

