name: Pre-submit tests

on:
  push:
    branches-ignore:
      - master
      - pr/*
      - jdk-17+35-custom

permissions:
  contents: read

jobs:
#  build-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#      - run: make -C lab build.jdk.case
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: make -C lab build.jdk.case
